MARKET 6513 Fix and Update Sample Hospitality App
NCR-Corporation/sample-app-burgers pull request #106
Opened 2023-12-01 17:05 UTC by cs185388

- Removed empty fields from menu items where data doesn't exist.
- Fixed images, links and menu items.
- Fixed formatting.

NOTE: Some of the work was done through the Menu Maker web app

2023-12-01 17:11 UTC, av185144 requested changes

2023-12-01 17:11 UTC, av185144 commented on code/BurgersUnlimited/settings.py
> +SECRET_KEY = 'NqYY0VNSYe7IOLoYD4Aa1WBIi*Gj4WATPl0y4Hes2tTWMmqfwB'
which environment is this?

2023-12-01 17:12 UTC, cs185388 commented on code/BurgersUnlimited/settings.py
> +SECRET_KEY = 'NqYY0VNSYe7IOLoYD4Aa1WBIi*Gj4WATPl0y4Hes2tTWMmqfwB'
I believe it's production, should we hide this?

2023-12-01 18:03 UTC, kk185256 commented on code/BurgersUnlimited/settings.py
> +SECRET_KEY = 'NqYY0VNSYe7IOLoYD4Aa1WBIi*Gj4WATPl0y4Hes2tTWMmqfwB'
oh wow you are right amoli this is public repo.. this is crazy

2023-12-04 15:22 UTC, cs185388 commented on code/BurgersUnlimited/settings.py
> +SECRET_KEY = 'NqYY0VNSYe7IOLoYD4Aa1WBIi*Gj4WATPl0y4Hes2tTWMmqfwB'
Yeah it was showing before I picked it up, I just updated it with the current one
But I agree with both of you and will remove it

2023-12-04 19:29 UTC, jg185352 approved these changes

2023-12-04 20:43 UTC, merged