Adding Menu Parsing File
NCR-Corporation/sample-app-burgers pull request #27
Opened 2021-07-20 21:51 UTC by tm185221

## Description
Adds the menu parsing file to the repo. This file is responsible for parsing the menu. 

## Testing
There is nothing to test for this change. The routes of the application were not changed.

## Ticket
MARKET-5092

2021-07-21 16:09 UTC, co185063 requested changes

2021-07-21 16:09 UTC, co185063 commented on code/menuParser.py
> +
extra line 🐧

2021-07-21 16:09 UTC, co185063 commented on code/menuParser.py
> +
extra lines 🐧

2021-07-21 16:09 UTC, co185063 commented on code/menuParser.py
> +
extra line 🐧

2021-07-21 16:09 UTC, co185063 commented on code/menuParser.py
> +
extra lines 🐧

2021-07-21 16:09 UTC, co185063 commented on code/menuParser.py
> +
extra lines 🐧

2021-07-21 16:09 UTC, co185063 commented on code/menuParser.py
> +
extra lines 🐧

2021-07-21 16:09 UTC, co185063 commented on code/menuParser.py
> +        if len(item['linkGroupIds'])!= 0:
In this line, I would try to do something like if !len(item['linkGroupIds']): Not sure if this line would work but I prefer to leave out the != 0 in expressions like these

2021-07-21 16:09 UTC, co185063 commented on code/menuParser.py
> +
Extra lines at the end of the file 🐧

2021-07-21 16:09 UTC, co185063 commented on code/menuParser.py
> +
extra lines

2021-07-21 16:09 UTC, co185063 commented on code/menuParser.py
> +                    'tags': item['tags'],'uniqueToppings':uniqueToppingsWithPrices,'sharedToppings':sharedToppingsWithPrices, 'groupToppings':groupToppingsWithPrices}
Can we align these two lines?

2021-07-21 16:09 UTC, co185063 commented on code/menuParser.py
> +    print(priceList)
Do we need this print statement?

2021-07-21 16:09 UTC, co185063 commented on code/menuParser.py
> +print(menuParsing())
Do we need this print statement?

2021-07-21 20:47 UTC, tm185221 commented on code/menuParser.py
> +        if len(item['linkGroupIds'])!= 0:
Here I am checking to see if the item has linkGroups. In the menu.json the linkGroupIds will either contain the linkgroupIds r be blank.

Would a better solution be:
`python
if not item['linkGroupIds]:
`

2021-07-23 16:29 UTC, co185063 commented on code/menuParser.py
> +                    'tags': item['tags'],'uniqueToppings':uniqueToppingsWithPrices,'sharedToppings':sharedToppingsWithPrices, 'groupToppings':groupToppingsWithPrices}
This conversation was marked as resolved but I don't see any changes or comments left to why we left it this way. I suggest

```
iteminfo = 
    {
        'id':lunchID ,
        'displayName':item['displayName'],
        'description':item['description'], 
        'price': item['currentPrice'],
        'tags': item['tags'],
        'uniqueToppings':uniqueToppingsWithPrices,
        'sharedToppings':sharedToppingsWithPrices, 
        'groupToppings':groupToppingsWithPrices
    }
```

Or compared to the original line but with a different formatting

```
iteminfo = 
    {
        "id":lunchID ,
        "displayName":item['displayName'],
        'description':item['description'], 
        'price': item['currentPrice'],
        'tags': item['tags'],
        'uniqueToppings':uniqueToppingsWithPrices,
        'sharedToppings':sharedToppingsWithPrices, 
        'groupToppings':groupToppingsWithPrices
    }
```

The differences between the first block of code and the second is that I updated the items id and displayName to use ' ' and not the " ".

2021-07-23 16:29 UTC, co185063 commented on code/menuParser.py
> +        if len(item['linkGroupIds'])!= 0:
I think that line should work. If you test it and it works def add that in in this line's place

2021-07-23 16:29 UTC, co185063 commented on code/menuParser.py
> +
Extra extra line 🐧

2021-07-26 16:17 UTC, kg185155 approved these changes

2021-07-26 16:49 UTC, co185063 approved these changes
LGTM!

2021-07-26 16:54 UTC, merged