Tm185221 lunch and dinner menu implementation
NCR-Corporation/sample-app-burgers pull request #44
Opened 2021-08-12 03:30 UTC by tm185221

## Description
This PR is removing the dependency of the catalog API and introducing the menu API into the burger demo site. It removes the current catalog pages and replaces them with temporary menu and item detail pages. There are 6 combinations in total: southland lunch / dinner , midtown lunch/dinner and highlands lunch / dinner.

## Screenshots/Screencasts
![1](https://user-images.githubusercontent.com/66689601/129133080-4e8471e8-a2bb-4f57-b90f-610ff59f4438.png)
![2](https://user-images.githubusercontent.com/66689601/129133087-75cb30c2-8089-40a4-8bf4-f9e3463c3834.png)

## Testing
Please outline how to test this fix or feature. Include all steps.

1.) Input credentials into the settings file. You will need to comment out the first set of keys. They are for the prod branch of the sample app. Use the dev keys. I can provide an updated settings file.
2.)  Paste this code at the bottom of the index.html file lines 151-153. 
`html
  <button type="button" class="btn btn-warning start-order" id="menu">
    Menu
  </button>`
3.) After updating the file. If you click on button you will be taken to the menu for midtown and the time of day it currently is (lunch/dinner)
![3](https://user-images.githubusercontent.com/66689601/129134014-0d4f2fb5-0b06-4aa9-978b-dafc27a31212.PNG)
4.) You can click on an item and be taken to its details page. It should show the picture and information about the item.
5.) To check the other locations: 'southland' and 'highland',  navigate to the index.js file inside of code/static/js, and alter line 80.
`js
var site = "midtown"
` to either 'highland' or 'southland'. _Be sure to use lowercase only._ Repeat steps 4 and 5.
6.) To change the time of day, navigate to the views.py found inside of code/burger and alter line 56. `time = request.session.get('time')` to `time="Dinner" or time="Lunch"`

## Ticket
Ticket Number

2021-08-13 19:20 UTC, co185063 requested changes

2021-08-13 19:20 UTC, co185063 commented on code/burger/views.py
> +    if 15.01 < hourAndTime < 23.59:
```
    time = datetime.datetime.now()
    hour = time.hour
    min = time.minute / 100
    hourAndTime = hour + min
    if 15.01 < hourAndTime < 23.59:
```

I think this batch of code is kind of clunky and overly complicated. Why not just
```
    time = datetime.datetime.now().hour
    if time > 14:
```
You don't really have to worry about the minutes because dinner will fall between the hours of 15 and 23.

2021-08-13 19:20 UTC, co185063 commented on code/menuParser.py
> +
Extra line 🐧

2021-08-13 19:20 UTC, co185063 commented on code/static/js/index.js
> +      // Does this cookie string begin with the name we want?
comment 🐧

2021-08-16 14:03 UTC, kg185155 reviewed
Beside's chase's comments, looks good

2021-08-16 20:39 UTC, tm185221 commented on code/burger/views.py
> +    if 15.01 < hourAndTime < 23.59:
Correct. Updated

2021-08-16 22:01 UTC, kg185155 approved these changes

2021-08-17 14:39 UTC, co185063 requested changes

2021-08-17 14:39 UTC, co185063 commented on code/menuParser.py
> +
extra line

2021-08-17 14:39 UTC, co185063 commented on code/menuParser.py
> +
extra line

2021-08-17 14:39 UTC, co185063 commented on code/menuParser.py
> +
extra line

2021-08-17 16:49 UTC, tm185221 commented on code/static/js/index.js
> +        console.log(data);
removed.

2021-08-17 17:05 UTC, co185063 approved these changes

2021-08-17 17:12 UTC, merged