TM185221 & KG185155- Frontend Modifiers Page
NCR-Corporation/sample-app-burgers pull request #72
Opened 2021-09-20 23:18 UTC by tm185221

## Description
This page implements the frontend design detailed in the figma page. 

## Screenshots/Screencasts
 🐈- Demo Kitty
 ![Frontend Mods](https://user-images.githubusercontent.com/66689601/134088634-6fd304dd-7df3-4ccf-88fc-ce4a243eef9d.gif)

 
 🔍 -Figma Standard
 https://www.figma.com/file/TdRUGgwZVKWD1vxizIrDJA/Hospitality-Sample-App?node-id=317%3A927
![111](https://user-images.githubusercontent.com/66689601/134088548-f0a7bac4-d533-472e-acf4-e26d06f2080e.PNG)  
![222](https://user-images.githubusercontent.com/66689601/134088547-cd42ab39-a2e2-4ee1-9a49-83c670df3259.PNG)

## Testing
Please outline how to test this fix or feature. Include all steps.
 1.) Start the Application on the Staging Environment
2.) Pick any site in the location modal
3.) Navigate to the dinner or lunch menu
4.) Pick a burger
5.) Add and remove toppings from the burger
6.) Add the item to the order {Ensure a modal pops up}
7.) Test checking out and continue ordering buttons

## Notes

_The demo headings for the toppings differs slightly from the figma file. I was told that this was fine._ 

## Ticket

_I will add this in tomorrow 👍🏾_

2021-09-21 14:02 UTC, co185063 requested changes

2021-09-21 14:02 UTC, co185063 commented on code/static/js/itemDetails.js
> +    if (includedItems.length > 0) {
this could just be if(includedItems.length)

2021-09-21 14:02 UTC, co185063 commented on code/static/js/itemDetails.js
> +    if (sharedToppings.length > 0) {
same here

2021-09-21 14:02 UTC, co185063 commented on code/static/js/itemDetails.js
> +    if (groupToppings.length > 0) {
same here

2021-09-21 14:02 UTC, co185063 commented on code/static/js/menu.js
> +    if (cart == null || cart.length == 0) {
if(cart == null || !cart.length)

2021-09-21 14:02 UTC, co185063 commented on code/templates/itemDetails.html
> +</style>
Can we add a css file so we can remove the in-html doc styling

2021-09-21 14:45 UTC, kg185155 commented on code/burger/views.py
> +                'menuLink': '/burger/menu/' + location.capitalize() + '/' + time
menuLink is used so that when you click "Back to menu" it goes back to the right menu

2021-09-21 14:45 UTC, kg185155 commented on code/static/js/cart.js
> +            total += +item.dataset.itemPrice;
the `+` in front of it is the same as `parseInt(item.dataset.itemPrice`. Converts string -> int

2021-09-29 20:39 UTC, co185063 approved these changes

2021-10-01 16:50 UTC, merged